"""initial schema

Revision ID: 5b08f4badaa1
Revises: 
Create Date: 2026-07-01 21:10:13.391770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b08f4badaa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('employee_key', sa.String(length=128), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pending_approval', sa.Boolean(), nullable=False),
    sa.Column('traces', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_employee_key'), ['employee_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_success'), ['success'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('employee_key', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('team_code', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('compressed_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('pending_approval', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_employee_key'), ['employee_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_last_active_at'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_team_code'), ['team_code'], unique=False)

    op.create_table('long_term_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_long_term_memories_employee_key'), ['employee_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_long_term_memories_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_long_term_memories_memory_id'), ['memory_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_role_code'), ['role_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_role_code'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_code'))

    op.drop_table('roles')
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_long_term_memories_memory_id'))
        batch_op.drop_index(batch_op.f('ix_long_term_memories_kind'))
        batch_op.drop_index(batch_op.f('ix_long_term_memories_employee_key'))

    op.drop_table('long_term_memories')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_team_code'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_target_type'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_last_active_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_employee_key'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_archived'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_success'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_employee_key'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
